// Curated topics. `reference` = TierLab's own (opinionated) take, best tier first.
// `stats` power the "Auto-tier from data" mode. `wikiLang`/`wikiSuffix` help the image finder.

export const CATEGORIES = {
  sports: { emoji: "🏀", tr: "Spor", en: "Sports" },
  food: { emoji: "🍽️", tr: "Yemek", en: "Food" },
  tech: { emoji: "💻", tr: "Teknoloji", en: "Tech" },
  games: { emoji: "🎮", tr: "Oyun", en: "Games" },
  science: { emoji: "🔭", tr: "Bilim", en: "Science" },
  life: { emoji: "📱", tr: "Hayat", en: "Life" },
};

const nba = (name, rings, mvp, fmvp, ppg, allnba, extra = {}) => ({ name, stats: { rings, mvp, fmvp, ppg, allnba }, ...extra });
const planet = (name, en, diameter, moons, au, gravity, note) => ({ name, en, stats: { diameter, moons, au, gravity }, note });

export const TOPICS = [
  {
    id: "nba-goats",
    cat: "sports",
    emoji: "🐐",
    title: { tr: "NBA'in En Büyükleri", en: "NBA All-Time Greats" },
    desc: { tr: "GOAT tartışmasını veriyle bitir.", en: "Settle the GOAT debate — with data." },
    source: "Basketball-Reference, regular season, approx. through 2024-25. FMVP award started in 1969.",
    wikiSuffix: " basketball",
    stats: [
      { key: "rings", tr: "Şampiyonluk", en: "Championships", higherIsBetter: true },
      { key: "mvp", tr: "MVP", en: "MVPs", higherIsBetter: true },
      { key: "fmvp", tr: "Finals MVP", en: "Finals MVPs", higherIsBetter: true },
      { key: "ppg", tr: "Sayı ort.", en: "Points / game", higherIsBetter: true },
      { key: "allnba", tr: "All-NBA", en: "All-NBA teams", higherIsBetter: true },
    ],
    items: [
      nba("Michael Jordan", 6, 5, 6, 30.1, 11),
      nba("LeBron James", 4, 4, 4, 27.0, 21),
      nba("Kareem Abdul-Jabbar", 6, 6, 2, 24.6, 15),
      nba("Magic Johnson", 5, 3, 3, 19.5, 10),
      nba("Larry Bird", 3, 3, 2, 24.3, 10),
      nba("Kobe Bryant", 5, 1, 2, 25.0, 15),
      nba("Tim Duncan", 5, 2, 3, 19.0, 15),
      nba("Shaquille O'Neal", 4, 1, 3, 23.7, 14),
      nba("Bill Russell", 11, 5, 0, 15.1, 11, { note: "The Finals MVP trophy is named after him." }),
      nba("Wilt Chamberlain", 2, 4, 1, 30.1, 10, { note: "Scored 100 points in one game (1962)." }),
      nba("Stephen Curry", 4, 2, 1, 24.8, 11),
      nba("Kevin Durant", 2, 1, 2, 27.2, 11),
      nba("Hakeem Olajuwon", 2, 1, 2, 21.8, 12),
      nba("Nikola Jokić", 1, 3, 1, 21.8, 7),
      nba("Giannis Antetokounmpo", 1, 2, 1, 23.9, 9),
      nba("Dirk Nowitzki", 1, 1, 1, 20.7, 12),
      nba("Oscar Robertson", 1, 1, 0, 25.7, 11, { note: "Averaged a triple-double in 1961-62." }),
      nba("Jerry West", 1, 0, 1, 27.0, 12, { note: "The NBA logo silhouette. Only Finals MVP from a losing team." }),
      nba("Karl Malone", 0, 2, 0, 25.0, 14),
      nba("Charles Barkley", 0, 1, 0, 22.1, 11),
      nba("Kevin Garnett", 1, 1, 0, 17.8, 9),
      nba("Moses Malone", 1, 3, 1, 20.3, 8),
      nba("Allen Iverson", 0, 1, 0, 26.7, 7),
      nba("Luka Dončić", 0, 0, 0, 28.7, 5),
    ],
    reference: [
      ["Michael Jordan", "LeBron James", "Kareem Abdul-Jabbar"],
      ["Magic Johnson", "Larry Bird", "Kobe Bryant", "Tim Duncan", "Shaquille O'Neal", "Bill Russell", "Wilt Chamberlain", "Stephen Curry"],
      ["Nikola Jokić", "Kevin Durant", "Hakeem Olajuwon", "Dirk Nowitzki", "Giannis Antetokounmpo", "Oscar Robertson", "Jerry West"],
      ["Karl Malone", "Charles Barkley", "Kevin Garnett", "Moses Malone", "Allen Iverson"],
      ["Luka Dončić"],
    ],
  },
  {
    id: "euroleague-legends",
    cat: "sports",
    emoji: "🏆",
    title: { tr: "EuroLeague Efsaneleri", en: "EuroLeague Legends" },
    desc: { tr: "Diamantidis mi, Spanoulis mi, Navarro mu?", en: "Diamantidis, Spanoulis or Navarro?" },
    wikiSuffix: " basketball",
    items: [
      { name: "Dimitris Diamantidis" }, { name: "Vassilis Spanoulis" }, { name: "Juan Carlos Navarro" },
      { name: "Šarūnas Jasikevičius" }, { name: "Theodoros Papaloukas" }, { name: "Dejan Bodiroga" },
      { name: "Nikos Galis" }, { name: "Arvydas Sabonis" }, { name: "Toni Kukoč" }, { name: "Dino Rađa" },
      { name: "Sergio Llull" }, { name: "Kyle Hines" }, { name: "Vasilije Micić" }, { name: "Shane Larkin" },
      { name: "Kostas Sloukas" }, { name: "Ramūnas Šiškauskas" }, { name: "Anthony Parker", wiki: "Anthony Parker (basketball)" },
      { name: "Luka Dončić" }, { name: "Mike James", wiki: "Mike James (basketball, born 1990)" }, { name: "Nikola Mirotić" },
    ],
    reference: [
      ["Dimitris Diamantidis", "Vassilis Spanoulis", "Juan Carlos Navarro", "Šarūnas Jasikevičius"],
      ["Theodoros Papaloukas", "Dejan Bodiroga", "Nikos Galis", "Arvydas Sabonis", "Sergio Llull", "Kyle Hines", "Toni Kukoč"],
      ["Vasilije Micić", "Shane Larkin", "Kostas Sloukas", "Dino Rađa", "Ramūnas Šiškauskas", "Anthony Parker", "Luka Dončić"],
      ["Mike James", "Nikola Mirotić"],
    ],
  },
  {
    id: "planets",
    cat: "science",
    emoji: "🪐",
    title: { tr: "Güneş Sistemi Gezegenleri", en: "Planets of the Solar System" },
    desc: { tr: "Pluto'yu da ekledik. Tartışmaya açığız.", en: "Pluto included. Fight us." },
    source: "NASA planetary fact sheets. Moon counts change as new moons are confirmed (approx. 2025).",
    wikiLang: "en",
    wikiSuffix: " planet",
    stats: [
      { key: "diameter", tr: "Çap (km)", en: "Diameter (km)", higherIsBetter: true },
      { key: "moons", tr: "Uydu sayısı", en: "Moons", higherIsBetter: true },
      { key: "au", tr: "Güneş'e uzaklık (AU)", en: "Distance from Sun (AU)", higherIsBetter: false },
      { key: "gravity", tr: "Yerçekimi (m/s²)", en: "Surface gravity (m/s²)", higherIsBetter: true },
    ],
    items: [
      planet("Merkür", "Mercury", 4879, 0, 0.39, 3.7, "A year there lasts 88 Earth days."),
      planet("Venüs", "Venus", 12104, 0, 0.72, 8.87, "A day on Venus is longer than its year."),
      planet("Dünya", "Earth", 12742, 1, 1.0, 9.81, "The only known place with tier lists."),
      planet("Mars", "Mars", 6779, 2, 1.52, 3.71, "Home of Olympus Mons, the tallest volcano in the Solar System."),
      planet("Jüpiter", "Jupiter", 139820, 95, 5.2, 24.79, "Its Great Red Spot is wider than Earth."),
      planet("Satürn", "Saturn", 116460, 274, 9.54, 10.44, "Less dense than water."),
      planet("Uranüs", "Uranus", 50724, 28, 19.2, 8.69, "Rolls around the Sun on its side."),
      planet("Neptün", "Neptune", 49244, 16, 30.1, 11.15, "Fastest winds in the Solar System."),
      planet("Plüton", "Pluto", 2377, 5, 39.5, 0.62, "Demoted to dwarf planet in 2006."),
    ].map((p) => ({ ...p, wiki: p.en === "Mercury" ? "Mercury (planet)" : p.en })),
    reference: [["Dünya", "Satürn"], ["Jüpiter", "Mars"], ["Neptün", "Uranüs"], ["Venüs", "Plüton"], ["Merkür"]],
  },
  {
    id: "programming-languages",
    cat: "tech",
    emoji: "👩‍💻",
    title: { tr: "Programlama Dilleri", en: "Programming Languages" },
    desc: { tr: "Yorum kısmında savaş çıkaran klasik.", en: "The classic comment-section war starter." },
    wikiSuffix: " programming language",
    items: ["Python", "JavaScript", "TypeScript", "Java", "C", "C++", "C#", "Go", "Rust", "Kotlin", "Swift", "PHP", "Ruby",
      "SQL", "R", "Scala", "Haskell", "Lua", "Dart", "Elixir", "Zig", "MATLAB", "COBOL", "Assembly"].map((name) => ({ name })),
    reference: [
      ["Python", "SQL", "TypeScript"],
      ["Rust", "Go", "C", "Kotlin", "C#"],
      ["Java", "C++", "JavaScript", "Swift", "Elixir", "Scala"],
      ["Ruby", "Dart", "Haskell", "Lua", "Zig", "R"],
      ["PHP", "MATLAB", "Assembly"],
      ["COBOL"],
    ],
  },
  {
    id: "data-engineering-tools",
    cat: "tech",
    emoji: "🛠️",
    title: { tr: "Veri Mühendisliği Araçları", en: "Data Engineering Tools" },
    desc: { tr: "Modern data stack'in hangi parçası gerçekten değerli?", en: "Which part of the modern data stack actually earns its keep?" },
    items: [
      { name: "PostgreSQL" }, { name: "DuckDB" }, { name: "dbt", wiki: "dbt (software)" }, { name: "Apache Spark" },
      { name: "Apache Airflow" }, { name: "Apache Kafka" }, { name: "Polars", wiki: "Polars (software)" }, { name: "Apache Iceberg" },
      { name: "Docker", wiki: "Docker (software)" }, { name: "BigQuery" }, { name: "Snowflake", wiki: "Snowflake Inc." },
      { name: "Dagster" }, { name: "Databricks" }, { name: "pandas", wiki: "Pandas (software)" }, { name: "Apache Flink" },
      { name: "Delta Lake" }, { name: "Kubernetes" }, { name: "Prefect" }, { name: "Airbyte" }, { name: "Fivetran" },
      { name: "Great Expectations" }, { name: "Excel", wiki: "Microsoft Excel", note: "Still the world's most popular database." },
    ],
    reference: [
      ["PostgreSQL", "DuckDB", "dbt", "Apache Spark"],
      ["Apache Airflow", "Apache Kafka", "Polars", "Apache Iceberg", "Docker", "BigQuery", "Snowflake"],
      ["Dagster", "Databricks", "pandas", "Apache Flink", "Delta Lake", "Kubernetes"],
      ["Prefect", "Airbyte", "Fivetran", "Great Expectations"],
      [],
      ["Excel"],
    ],
  },
  {
    id: "turkish-breakfast",
    cat: "food",
    emoji: "🍳",
    title: { tr: "Türk Kahvaltısı", en: "Turkish Breakfast" },
    desc: { tr: "Menemen soğanlı mı olur? Önce bunu sırala.", en: "The world's best breakfast, ranked item by item." },
    wikiLang: "tr",
    items: [
      { name: "Menemen" }, { name: "Çay", en: "Turkish tea", wiki: "Türk çayı" }, { name: "Simit" },
      { name: "Kaymak & bal", en: "Kaymak & honey", wiki: "Kaymak" }, { name: "Sucuklu yumurta", en: "Eggs with sucuk", wiki: "Sucuk" },
      { name: "Beyaz peynir", en: "White cheese" }, { name: "Su böreği", en: "Su böreği" }, { name: "Pişi", en: "Pişi (fried dough)" },
      { name: "Gözleme" }, { name: "Kuymak", en: "Kuymak (cheese fondue)" }, { name: "Siyah zeytin", en: "Black olives", wiki: "Zeytin" },
      { name: "Çılbır", en: "Çılbır (poached eggs)" }, { name: "Kaşar", en: "Kaşar cheese", wiki: "Kaşar peyniri" },
      { name: "Domates & salatalık", en: "Tomato & cucumber", wiki: "Domates" }, { name: "Poğaça" },
      { name: "Tahin pekmez", en: "Tahini & molasses", wiki: "Tahin" }, { name: "Sigara böreği", en: "Cigar börek" },
      { name: "Bazlama" }, { name: "Acuka" }, { name: "Vişne reçeli", en: "Sour cherry jam", wiki: "Reçel" },
      { name: "Yeşil zeytin", en: "Green olives", wiki: "Zeytin" }, { name: "Haşlanmış yumurta", en: "Boiled egg", wiki: "Haşlanmış yumurta" },
      { name: "Gül reçeli", en: "Rose jam", wiki: "Gül reçeli" }, { name: "Nutella" },
    ],
    reference: [
      ["Menemen", "Çay", "Simit", "Kaymak & bal", "Sucuklu yumurta"],
      ["Beyaz peynir", "Su böreği", "Pişi", "Gözleme", "Kuymak", "Siyah zeytin", "Çılbır"],
      ["Kaşar", "Domates & salatalık", "Poğaça", "Tahin pekmez", "Sigara böreği", "Bazlama", "Acuka"],
      ["Vişne reçeli", "Yeşil zeytin", "Haşlanmış yumurta", "Gül reçeli"],
      ["Nutella"],
    ],
  },
  {
    id: "turkish-street-food",
    cat: "food",
    emoji: "🥙",
    title: { tr: "Sokak Lezzetleri", en: "Turkish Street Food" },
    desc: { tr: "Gece 2'de hangisi seni kurtarır?", en: "What saves you at 2 a.m.?" },
    wikiLang: "tr",
    items: [
      { name: "Döner" }, { name: "Lahmacun" }, { name: "Tantuni" }, { name: "Kokoreç" }, { name: "Midye dolma", en: "Stuffed mussels" },
      { name: "Balık ekmek", en: "Fish sandwich" }, { name: "Islak hamburger", en: "Wet burger" }, { name: "Tavuk pilav", en: "Chicken & rice", wiki: "Pilav" },
      { name: "Dürüm" }, { name: "Kumru" }, { name: "Boyoz" }, { name: "Çiğ köfte" }, { name: "Kestane kebap", en: "Roasted chestnuts", wiki: "Kestane" },
      { name: "Közde mısır", en: "Grilled corn", wiki: "Mısır" }, { name: "Simit" }, { name: "Gözleme" }, { name: "Kumpir" },
      { name: "Nohutlu pilav", en: "Rice with chickpeas", wiki: "Pilav" }, { name: "Waffle" },
    ],
    reference: [
      ["Döner", "Lahmacun", "Tantuni", "Kokoreç", "Midye dolma"],
      ["Balık ekmek", "Islak hamburger", "Tavuk pilav", "Dürüm", "Kumru", "Boyoz"],
      ["Çiğ köfte", "Kestane kebap", "Közde mısır", "Simit", "Gözleme"],
      ["Kumpir", "Nohutlu pilav"],
      ["Waffle"],
    ],
  },
  {
    id: "turkish-desserts",
    cat: "food",
    emoji: "🍮",
    title: { tr: "Türk Tatlıları", en: "Turkish Desserts" },
    desc: { tr: "Şerbetli mi sütlü mü? Ebedi savaş.", en: "Syrup vs. milk: the eternal war." },
    wikiLang: "tr",
    items: [
      { name: "Baklava" }, { name: "Künefe" }, { name: "Katmer" }, { name: "Sütlaç", en: "Rice pudding" }, { name: "Kazandibi" },
      { name: "Tavuk göğsü", en: "Chicken breast pudding" }, { name: "Lokum", en: "Turkish delight" }, { name: "Aşure", en: "Noah's pudding" },
      { name: "Revani" }, { name: "Tulumba" }, { name: "Kalburabastı" }, { name: "Profiterol", en: "Profiteroles" }, { name: "Trileçe" },
      { name: "Sarığı burma" }, { name: "Kadayıf" }, { name: "Şekerpare" }, { name: "Helva", en: "Halva" },
      { name: "Maraş dondurması", en: "Maraş ice cream" }, { name: "Supangle" }, { name: "Güllaç" }, { name: "Keşkül" },
    ],
    reference: [
      ["Baklava", "Künefe", "Katmer", "Maraş dondurması"],
      ["Sütlaç", "Kazandibi", "Sarığı burma", "Profiterol", "Trileçe"],
      ["Tavuk göğsü", "Lokum", "Kadayıf", "Güllaç", "Supangle", "Tulumba"],
      ["Revani", "Şekerpare", "Kalburabastı", "Helva", "Keşkül"],
      ["Aşure"],
    ],
  },
  {
    id: "video-games",
    cat: "games",
    emoji: "🕹️",
    title: { tr: "Efsane Oyunlar", en: "Legendary Video Games" },
    desc: { tr: "Steam kütüphanendeki gerçek GOAT hangisi?", en: "Which one is the real GOAT of your library?" },
    wikiSuffix: " video game",
    items: [
      { name: "Titanfall 2" }, { name: "Rainbow Six Siege", wiki: "Tom Clancy's Rainbow Six Siege" },
      { name: "Star Wars Battlefront II", wiki: "Star Wars Battlefront II (2017 video game)" },
      { name: "Watch Dogs" }, { name: "Watch Dogs 2" }, { name: "Portal 2" }, { name: "Half-Life 2" },
      { name: "Counter-Strike 2" }, { name: "Dota 2" }, { name: "GTA V", wiki: "Grand Theft Auto V" },
      { name: "The Witcher 3", wiki: "The Witcher 3: Wild Hunt" }, { name: "Elden Ring" },
      { name: "Red Dead Redemption 2" }, { name: "Skyrim", wiki: "The Elder Scrolls V: Skyrim" }, { name: "Terraria" },
      { name: "Stardew Valley" }, { name: "Hades", wiki: "Hades (video game)" }, { name: "Baldur's Gate 3" },
      { name: "Cyberpunk 2077" }, { name: "Minecraft" }, { name: "League of Legends" }, { name: "Valorant" },
      { name: "Fortnite" }, { name: "Hollow Knight" },
    ],
    reference: [
      ["Titanfall 2", "Red Dead Redemption 2", "The Witcher 3", "Portal 2", "Elden Ring"],
      ["Half-Life 2", "Minecraft", "Baldur's Gate 3", "Hollow Knight", "Hades", "Skyrim", "GTA V"],
      ["Rainbow Six Siege", "Watch Dogs 2", "Terraria", "Stardew Valley", "Counter-Strike 2", "Cyberpunk 2077", "Dota 2"],
      ["Star Wars Battlefront II", "Valorant", "League of Legends", "Watch Dogs"],
      ["Fortnite"],
    ],
  },
  {
    id: "social-media",
    cat: "life",
    emoji: "📲",
    title: { tr: "Sosyal Medya Uygulamaları", en: "Social Media Apps" },
    desc: { tr: "Ekran sürene göre değil, gerçekten değerine göre.", en: "Rank by real value, not by screen time." },
    items: [
      { name: "YouTube" }, { name: "WhatsApp" }, { name: "Instagram" }, { name: "TikTok" }, { name: "X (Twitter)", wiki: "Twitter" },
      { name: "Reddit" }, { name: "Discord" }, { name: "Telegram", wiki: "Telegram (software)" }, { name: "LinkedIn" },
      { name: "Facebook" }, { name: "Snapchat" }, { name: "Pinterest" }, { name: "Twitch", wiki: "Twitch (service)" },
      { name: "Threads", wiki: "Threads (social network)" }, { name: "Bluesky" }, { name: "BeReal" }, { name: "Ekşi Sözlük" },
    ],
    reference: [
      ["YouTube", "WhatsApp", "Discord"],
      ["Reddit", "Telegram", "Instagram"],
      ["LinkedIn", "Twitch", "X (Twitter)", "Pinterest", "Ekşi Sözlük"],
      ["TikTok", "Bluesky", "Snapchat", "Threads"],
      ["Facebook", "BeReal"],
    ],
  },
];

export const findTopic = (id) => TOPICS.find((t) => t.id === id) || null;
